#!/bin/bash

#SBATCH --partition=amd-longq
#SBATCH --nodes=1
#SBATCH -c20
#SBATCH --gres=gpu:1

#module purge 
module load easybuild
module load vis/OpenCV/3.1.0-foss-2016b
module load cuda90/toolkit/9.0.176
module load cudnn/7.0
module load devel/CMake/3.5.2-foss-2016b

#CUDA_VISIBLE_DEVICES=0

#execute application
python /home/icha/compress_bnn/src/experiment.py

# exit
exit 0
